name: manual_speech_to_text
description: A Flutter package that provides manual control over speech-to-text functionality, allowing continuous listening with custom start, pause, resume, and stop callbacks without automatic pauses during speech breaks.
version: 1.0.3
homepage: https://github.com/sagarkalel/manual_speech_to_text
repository: https://github.com/sagarkalel/manual_speech_to_text
issue_tracker: https://github.com/sagarkalel/manual_speech_to_text/issues
documentation: https://github.com/sagarkalel/manual_speech_to_text/blob/main/README.md

platforms:
  android:
  ios:
  web:
  windows:
  linux:
  macos:

environment:
  sdk: ^3.5.0
  flutter: '>=1.17.0'

topics:
  - speech-to-text
  - flutter
  - voice-recognition
  - text-processing
  - audio

keywords:
  - speech to text
  - manual speech to text
  - continuous listening
  - voice recognition
  - flutter speech
  - speech recognition
  - live transcription
  - manual control
  - speech to text ultra
  - stt

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: